# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!
use_frameworks!

target 'ShiponK' do

pod 'IQKeyboardManager'
pod 'AFNetworking', '< 2.6.1'
pod 'MBProgressHUD', '~> 0.9.2'
pod 'AFDropdownNotification', '~> 1.0'
pod 'iOS-Slide-Menu'
#pod 'SDWebImage'
pod 'UIActivityIndicator-for-SDWebImage'
pod 'GoogleMaps'
pod "FBSDKCoreKit";
pod "FBSDKLoginKit";
pod "FBSDKShareKit";
pod "FBSDKMessengerShareKit";
pod 'Fabric'
pod 'TwitterKit'
pod 'TwitterCore'
pod 'Google/SignIn'

end


